// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Article: typeof import('./src/components/smart/Articles/Article.vue')['default']
    CarbonBackToTop: typeof import('~icons/carbon/back-to-top')['default']
    CarbonCalendar: typeof import('~icons/carbon/calendar')['default']
    CarbonHome: typeof import('~icons/carbon/home')['default']
    CarbonMenu: typeof import('~icons/carbon/menu')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSearch: typeof import('~icons/carbon/search')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CheckButton: typeof import('./src/components/building/CheckButton/CheckButton.vue')['default']
    CircleBlockBase: typeof import('./src/components/smart/WhoAmI/CircleBlockBase.vue')['default']
    Footer: typeof import('./src/components/building/Footer/Footer.vue')['default']
    Icon: typeof import('~icons/ic/on')['default']
    IconifyIcon: typeof import('~icons/ic/onify-icon')['default']
    ImageThree: typeof import('./src/components/building/Image/ImageThree.vue')['default']
    ImageTwo: typeof import('./src/components/building/Image/ImageTwo.vue')['default']
    Input: typeof import('./src/components/building/Input/Input.vue')['default']
    Latest: typeof import('./src/components/smart/Articles/Latest.vue')['default']
    Navbar: typeof import('./src/components/building/Navigation/Navbar.vue')['default']
    Paginate: typeof import('./src/components/building/Pagination/Paginate.vue')['default']
    Post: typeof import('./src/components/smart/Articles/Post.vue')['default']
    Share: typeof import('./src/components/building/Button/Share.vue')['default']
    Tag: typeof import('./src/components/building/Button/Tag.vue')['default']
    Textarea: typeof import('./src/components/building/TextArea/Textarea.vue')['default']
    TextArea: typeof import('./src/components/building/TextArea/TextArea.vue')['default']
    ToTopBtn: typeof import('./src/components/building/Button/ToTopBtn.vue')['default']
    UilGithub: typeof import('~icons/uil/github')['default']
    ULBase: typeof import('./src/components/smart/WhoAmI/ULBase.vue')['default']
  }
}

export { }
